/*
C ++ Programming Assessment Test
• Write a program to demonstrate a Rock Paper Scissor Game.
• Display the Menu using appropriate codes.
• For Menu kinds of Programming , use the core logic of Loops/conditional statements.
• You need to strictly follow the syntaxes’s of that logic which you are using.
• Write the necessary comments for better understanding to you as well as to the 
faculty.
Project Requirements : 
• Invoke the particular Method/Function through object , in which you are writing your
logic.
• Use this function :
• srand(time(0));
• (rand()%3)+1; -> Generating for random no.s from computer’s end.
• Use library header files i.e #include<stdlib.h> and #include<ctime> for above logic if 
necessary.
• Add the necessary comments for better understanding of code.
1) Below is the The Program flow.
Program Flow:
1) Accept the Name:
2) Enter No. of Rounds to Play.
3) Select your Choice ?
4) This is Round 1 
5) This is Round 2
6) This is Round 3
*/

#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <time.h>

using namespace std;

int main(){

    string name,waste;
    int choice=0,round,start=1,number;
    int computer=0,player=0;

    // NAME DESCRIPTION
    cout<<"\n\n #---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#\n" <<endl;
    cout<<"                            NAME   \n"<<endl;
    cout<<"#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#\n"<<endl;

    cout<<"Enter the name : ";
    getline(cin,name);

    //ROUND DESCRIPTION
    cout<<"\n#---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#\n"<<endl;
    cout<<"                      ROUNDS\n"<<endl;
    cout<<" #---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#\n"<<endl;

    cout<<name<<" How Many Rounds You Want To Play ?: ";
    cin>>round;

    do{
        
    //RANDOM VALUE GENERATED BY COMPUTER 
    srand(time(0));
    number = rand() % 3 + 1;

    cout<<" #---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#\n"<<endl;
    cout<<"                             GAME\n"<<endl;
    cout<<" #---#---#---#---#---#---#---#---#---#---#---#---#---#---#---#\n"<<endl;

    // SCORING SECTION

    cout<<" Round No  : "<<start<<"/"<<round <<endl<<endl;
    cout<<" "<<name<<"'s "<<" Score = "<<player <<endl<<endl;
    cout<<" Computer Score = "<<computer<<endl<<endl;

    cout<<" 1) ROCK \n\n 2) PAPER \n\n 3) SCISSOR \n"<<endl;

    //player choice part 
    cout<<" Select Your Choice : ";
    cin>>choice;
    cout<<"\n"<<endl;

    // computer choice part
    cout<<" Computer Choice is : "<<number<<"\n"<<endl;
    cout<<""<<endl;

    // BASIC RULE OF ROCK , PAPER , SCISSOR GAME LIKE ROCK IS STRONGER THAN SCISSOR BUT WEAKER THAN PAPER ETC...
    if(choice == number){
        cout<<" \n DRAW\n\n"<<endl;
    }
    
    if (choice == 1 && number == 3){
        if(choice < number){
            player++;
        }
    }

    else if(choice == 1 && number == 2){
        if(choice < number){
            computer++;
        }
    }

    else if(choice == 2 && number == 3){
        if(number > choice){
            computer++;
        }
    }
    
    else if(choice == 2 && number == 1){
        if(choice > number){
            player++;
            
        }
    }
    else if(choice == 3 && number == 1){
        if(choice > number){
            computer++;
        }
    }
    else if(choice == 3 && number == 2){
        if(number < choice){
            player++;

        }
    }
    // PRESSING ANY KEY FEATURE 
    cout<<" Press Any Key To Continue...And Then Enter.... ";
    cin>>waste;

    cout<<"\n";

    start++;

    }while(round >= start);

    cout<<"\n";

    // FINAL SCORE
    cout<<"              -- Final Score is --   \n"<<endl;

    cout<<" "<<name<<"'s "<<" Score = "<<player <<endl<<endl;
    cout<<" Computer Score = "<<computer<<endl<<endl;

    // WHO WIN THE GAME ?
    if(player > computer){
        cout<<name<<" you won the game "<<endl;
    }

    else if(player < computer){
        cout<<name<<" you lose the game "<<endl;
    }

    else if( player == computer){
        cout<<" Match Draw ... ";
    }

    return 0;
}